### PR TITLE
Edited Readme file

### PR DESCRIPTION
**Pull request by davitomix**
Edit readme file.

### CODE REVIEW

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by samgaco** [comment]
### Hi @geraldgsh and @davitomix :hand: 

### Your project looks perfect :clap: You are approved! Congratulations :tada: 

### Keep doing this kind of good work moving on :muscle:

**Comment by geraldgsh** [comment]
Thanks @Torres-ssf @samgaco for taking time to review our code :)

**Comment by davitomix** [comment]
Thanks @Torres-ssf  @samgaco

**Pull request merged**
